ifeq ("$(ASYLUM_INFRA_HOME)","")
$(error Environment variable "ASYLUM_INFRA_HOME" must be set)
endif

IP_DEPS       = lib		\
		OpenBlaze8	\
		kcpsm3     	\
		gated_clock

include $(ASYLUM_INFRA_HOME)/mk/ip.mk
